import Foundation

enum WorkspaceSection: String, CaseIterable, Identifiable {
    case library
    case inbox
    case wiki
    case papers
    case concepts
    case methods
    case gaps
    case projects
    case graph
    case llmLab
    case settings

    var id: String {
        rawValue
    }

    var title: String {
        switch self {
        case .library:
            return "Library"
        case .inbox:
            return "Inbox"
        case .wiki:
            return "Wiki"
        case .papers:
            return "Papers"
        case .concepts:
            return "Concepts"
        case .methods:
            return "Methods"
        case .gaps:
            return "Gaps"
        case .projects:
            return "Projects"
        case .graph:
            return "Graph"
        case .llmLab:
            return "LLM Lab"
        case .settings:
            return "Settings"
        }
    }

    var systemImage: String {
        switch self {
        case .library:
            return "books.vertical"
        case .inbox:
            return "tray"
        case .wiki:
            return "doc.text"
        case .papers:
            return "doc.richtext"
        case .concepts:
            return "lightbulb"
        case .methods:
            return "square.stack.3d.up"
        case .gaps:
            return "scope"
        case .projects:
            return "folder"
        case .graph:
            return "point.3.connected.trianglepath.dotted"
        case .llmLab:
            return "brain"
        case .settings:
            return "gearshape"
        }
    }

    var summary: String {
        switch self {
        case .library:
            return "Track papers, reading state, tags, and import status."
        case .inbox:
            return "Stage incoming PDFs before they are normalized into raw/papers."
        case .wiki:
            return "Browse Markdown knowledge pages generated by you or the LLM."
        case .papers:
            return "Open paper summaries, annotations, and bibliography links."
        case .concepts:
            return "Capture reusable concepts and backlinks across the workspace."
        case .methods:
            return "Document methods, experiments, and reusable analysis patterns."
        case .gaps:
            return "Collect candidate research gaps and evidence trails."
        case .projects:
            return "Keep project-specific context, plans, and milestones."
        case .graph:
            return "Visualize or inspect knowledge relationships when graph support lands."
        case .llmLab:
            return "Run structured prompts, summaries, and gap-finding workflows."
        case .settings:
            return "Configure workspace, PDF, LLM, and external tool settings."
        }
    }
}